# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Minos"
license = "MIT"
licenselink = "https://github.com/joseluisq/hugo-theme-minos.git/blob/master/LICENSE.md"
description = "A simple and retro styled theme ported from Hexo"
homepage = "https://github.com/joseluisq/hugo-theme-minos.git"
tags = ["blog", "minimal"]
features = ["blog", ""]
min_version = 0.20

[author]
  name = "Jose Quintana"
  homepage = "https://github.com/joseluisq"

# If porting an existing theme
[original]
  name = "Minos"
  homepage = "https://github.com/ppoffice/hexo-theme-minos"
  repo = "https://github.com/ppoffice/hexo-theme-minos"
